apiVersion: v1 # service object belongs from version V1
kind: Service # Object Type.
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP # Type of Service.
  selector:
    component: web # for client (Networking)
  ports:
    - port: 3000
      targetPort: 3000

